format = """
$python\
$directory\
[\uE0B0](fg:#4c566a bg:#ffffff)\
$git_branch\
$git_status\
[\uE0B0](fg:#ffffff)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#4c566a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "ï“¢"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Game" = "ó°œƒ"

[git_branch]
symbol = "ï˜"
style = "bg:#ffffff"
format = '[[ $symbol $branch ](fg:#4c566a bg:#ffffff)]($style)'

[git_status]
style = "bg:#ffffff"
format = '[[($all_status$ahead_behind )](fg:#4c566a bg:#ffffff)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#000000)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = "ó°™²"
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#a2f396 bg:#000000)]($style)'
detect_extensions = ['c','h','cpp','hpp']

[python]
style = "bg:#000000 fg:#7685a5"
format = '[$symbol$pyenv_prefix(\($virtualenv\)) ]($style)'
pyenv_version_name = true

[localip]
ssh_only = false
format = '@[$localipv4](bold blue) '
disabled = false


[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ff9fbb "
format = '[[ ïº $time ](fg:#ffffff bg:#ff9fbb )]($style)'
